import { useContext, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import ClientOnly from "@/components/ClientOnly";
import WorkBoard from "./components/WorkBoard/WorkBoard";

import UserContext from "@/contexts/UserContext";

export default function Home() {
  const router = useRouter();
  const { user, setUser } = useContext(UserContext);

  useEffect(() => {
    const isAuthenticated = sessionStorage.getItem("userID");
    if (!isAuthenticated) {
      router.push("/login");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ClientOnly>
          <WorkBoard />
        </ClientOnly>
      </main>
    </>
  );
}
